include_guard(DIRECTORY)

set(RAIN_REPO_DIR ${CMAKE_CURRENT_LIST_DIR}/..)
set(RAIN_CMAKE_DIR ${RAIN_REPO_DIR}/cmake)
set(RAIN_TARGETS_DIR ${RAIN_REPO_DIR}/targets)
set(RAIN_MODULES_DIR ${RAIN_REPO_DIR}/modules)
set(RAIN_SOURCES_DIR ${RAIN_REPO_DIR}/srcs)
set(RAIN_TESTS_DIR ${RAIN_REPO_DIR}/tests)
